// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rtqeHxaDTf3jEdnrLWLsJW
// Component: 1BdePqOzkHIJ

import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import { ThemeValue, useTheme } from "./PlasmicGlobalVariant__Theme"; // plasmic-import: kzqGCbXk1j_o/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_copy_of_todo_mvc.module.css"; // plasmic-import: rtqeHxaDTf3jEdnrLWLsJW/projectcss
import sty from "./PlasmicTask.module.css"; // plasmic-import: 1BdePqOzkHIJ/css

export type PlasmicTask__VariantMembers = {
  state: "checked" | "editing";
};
export type PlasmicTask__VariantsArgs = {
  state?: SingleChoiceArg<"checked" | "editing">;
};
type VariantPropType = keyof PlasmicTask__VariantsArgs;
export const PlasmicTask__VariantProps = new Array<VariantPropType>("state");

export type PlasmicTask__ArgsType = {
  children?: React.ReactNode;
};
type ArgPropType = keyof PlasmicTask__ArgsType;
export const PlasmicTask__ArgProps = new Array<ArgPropType>("children");

export type PlasmicTask__OverridesType = {
  root?: p.Flex<"div">;
  img?: p.Flex<"img">;
  textInput?: p.Flex<"input">;
  button?: p.Flex<"button">;
  textbox?: p.Flex<"input">;
};

export interface DefaultTaskProps {
  children?: React.ReactNode;
  state?: SingleChoiceArg<"checked" | "editing">;
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicTask__RenderFunc(props: {
  variants: PlasmicTask__VariantsArgs;
  args: PlasmicTask__ArgsType;
  overrides: PlasmicTask__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  const stateSpecs = React.useMemo(
    () => [
      {
        path: "state",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.state
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = p.useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries,
    $refs
  });

  const globalVariants = ensureGlobalVariants({
    theme: useTheme()
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root,
        {
          [sty.rootglobal_theme_dark]: hasVariant(
            globalVariants,
            "theme",
            "dark"
          ),
          [sty.rootglobal_theme_dark_state_editing]:
            hasVariant($state, "state", "editing") &&
            hasVariant(globalVariants, "theme", "dark"),
          [sty.rootstate_checked]: hasVariant($state, "state", "checked"),
          [sty.rootstate_editing]: hasVariant($state, "state", "editing")
        }
      )}
    >
      <div
        className={classNames(projectcss.all, sty.freeBox__xCu7R, {
          [sty.freeBoxglobal_theme_dark_state_editing__xCu7Robf95UEyba]:
            hasVariant($state, "state", "editing") &&
            hasVariant(globalVariants, "theme", "dark"),
          [sty.freeBoxstate_editing__xCu7RuEyba]: hasVariant(
            $state,
            "state",
            "editing"
          )
        })}
      >
        {(hasVariant($state, "state", "editing") ? false : true) ? (
          <div
            className={classNames(projectcss.all, sty.freeBox__z2Uyo, {
              [sty.freeBoxstate_checked__z2UyonYjWw]: hasVariant(
                $state,
                "state",
                "checked"
              ),
              [sty.freeBoxstate_checked_global_theme_dark__z2UyonYjWwObf95]:
                hasVariant($state, "state", "checked") &&
                hasVariant(globalVariants, "theme", "dark"),
              [sty.freeBoxstate_editing__z2UyouEyba]: hasVariant(
                $state,
                "state",
                "editing"
              )
            })}
          >
            {(hasVariant($state, "state", "checked") ? true : false) ? (
              <img
                data-plasmic-name={"img"}
                data-plasmic-override={overrides.img}
                alt={""}
                className={classNames(projectcss.all, projectcss.img, sty.img, {
                  [sty.imgstate_checked]: hasVariant(
                    $state,
                    "state",
                    "checked"
                  ),
                  [sty.imgstate_checked_global_theme_dark]:
                    hasVariant($state, "state", "checked") &&
                    hasVariant(globalVariants, "theme", "dark"),
                  [sty.imgstate_editing]: hasVariant($state, "state", "editing")
                })}
                src={
                  hasVariant($state, "state", "checked")
                    ? ("data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxZW0iIGhlaWdodD0iMWVtIiB2aWV3Qm94PSIwIDAgNTEyIDUxMiIgc3Ryb2tlLXdpZHRoPSIwIiBmaWxsPSJjdXJyZW50Q29sb3IiIHN0cm9rZT0iY3VycmVudENvbG9yIiBzdHlsZT0iZmlsbDogcmdiKDQsIDE0MywgNjQpOyI+PHBhdGggZD0iTTE3My44OTggNDM5LjQwNGwtMTY2LjQtMTY2LjRjLTkuOTk3LTkuOTk3LTkuOTk3LTI2LjIwNiAwLTM2LjIwNGwzNi4yMDMtMzYuMjA0YzkuOTk3LTkuOTk4IDI2LjIwNy05Ljk5OCAzNi4yMDQgMEwxOTIgMzEyLjY5IDQzMi4wOTUgNzIuNTk2YzkuOTk3LTkuOTk3IDI2LjIwNy05Ljk5NyAzNi4yMDQgMGwzNi4yMDMgMzYuMjA0YzkuOTk3IDkuOTk3IDkuOTk3IDI2LjIwNiAwIDM2LjIwNGwtMjk0LjQgMjk0LjQwMWMtOS45OTggOS45OTctMjYuMjA3IDkuOTk3LTM2LjIwNC0uMDAxeiIvPjwvc3ZnPg==" as const)
                    : ("data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxZW0iIGhlaWdodD0iMWVtIiB2aWV3Qm94PSIwIDAgNTEyIDUxMiIgc3Ryb2tlLXdpZHRoPSIwIiBmaWxsPSJjdXJyZW50Q29sb3IiIHN0cm9rZT0iY3VycmVudENvbG9yIj48cGF0aCBkPSJNMTczLjg5OCA0MzkuNDA0bC0xNjYuNC0xNjYuNGMtOS45OTctOS45OTctOS45OTctMjYuMjA2IDAtMzYuMjA0bDM2LjIwMy0zNi4yMDRjOS45OTctOS45OTggMjYuMjA3LTkuOTk4IDM2LjIwNCAwTDE5MiAzMTIuNjkgNDMyLjA5NSA3Mi41OTZjOS45OTctOS45OTcgMjYuMjA3LTkuOTk3IDM2LjIwNCAwbDM2LjIwMyAzNi4yMDRjOS45OTcgOS45OTcgOS45OTcgMjYuMjA2IDAgMzYuMjA0bC0yOTQuNCAyOTQuNDAxYy05Ljk5OCA5Ljk5Ny0yNi4yMDcgOS45OTctMzYuMjA0LS4wMDF6Ii8+PC9zdmc+" as const)
                }
              />
            ) : null}
          </div>
        ) : null}
      </div>
      <div
        className={classNames(projectcss.all, sty.freeBox___1XUs7, {
          [sty.freeBoxglobal_theme_dark___1XUs7Obf95]: hasVariant(
            globalVariants,
            "theme",
            "dark"
          ),
          [sty.freeBoxglobal_theme_dark_state_editing___1XUs7Obf95UEyba]:
            hasVariant($state, "state", "editing") &&
            hasVariant(globalVariants, "theme", "dark"),
          [sty.freeBoxstate_editing___1XUs7UEyba]: hasVariant(
            $state,
            "state",
            "editing"
          )
        })}
      >
        {(hasVariant($state, "state", "editing") ? false : true) ? (
          <div
            className={classNames(projectcss.all, sty.freeBox__hs7Ho, {
              [sty.freeBoxstate_checked__hs7HonYjWw]: hasVariant(
                $state,
                "state",
                "checked"
              ),
              [sty.freeBoxstate_editing__hs7HouEyba]: hasVariant(
                $state,
                "state",
                "editing"
              )
            })}
          >
            {p.renderPlasmicSlot({
              defaultContents: "Some kind of text here",
              value: args.children,
              className: classNames(sty.slotTargetChildren, {
                [sty.slotTargetChildrenglobal_theme_dark]: hasVariant(
                  globalVariants,
                  "theme",
                  "dark"
                ),
                [sty.slotTargetChildrenstate_checked]: hasVariant(
                  $state,
                  "state",
                  "checked"
                ),
                [sty.slotTargetChildrenstate_checked_global_theme_dark]:
                  hasVariant($state, "state", "checked") &&
                  hasVariant(globalVariants, "theme", "dark"),
                [sty.slotTargetChildrenstate_editing]: hasVariant(
                  $state,
                  "state",
                  "editing"
                )
              })
            })}
          </div>
        ) : null}
        {(hasVariant($state, "state", "editing") ? true : false) ? (
          <input
            data-plasmic-name={"textInput"}
            data-plasmic-override={overrides.textInput ?? overrides.textbox}
            className={classNames(
              projectcss.all,
              projectcss.input,
              sty.textInput,
              {
                [sty.textInputglobal_theme_dark_state_editing]:
                  hasVariant($state, "state", "editing") &&
                  hasVariant(globalVariants, "theme", "dark"),
                [sty.textInputstate_editing]: hasVariant(
                  $state,
                  "state",
                  "editing"
                )
              }
            )}
            placeholder={"Some placeholder text" as const}
            type={"text" as const}
          />
        ) : null}
        {(hasVariant($state, "state", "editing") ? false : true) ? (
          <div
            className={classNames(projectcss.all, sty.freeBox__tfpXf, {
              [sty.freeBoxstate_editing__tfpXfuEyba]: hasVariant(
                $state,
                "state",
                "editing"
              )
            })}
          >
            <button
              data-plasmic-name={"button"}
              data-plasmic-override={overrides.button}
              className={classNames(
                projectcss.all,
                projectcss.button,
                projectcss.__wab_text,
                sty.button,
                {
                  [sty.buttonstate_editing]: hasVariant(
                    $state,
                    "state",
                    "editing"
                  )
                }
              )}
            >
              {"\u00d7"}
            </button>
          </div>
        ) : null}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "img", "textInput", "textbox", "button"],
  img: ["img"],
  textInput: ["textInput", "textbox"],
  button: ["button"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  img: "img";
  textInput: "input";
  button: "button";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTask__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTask__VariantsArgs;
    args?: PlasmicTask__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicTask__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicTask__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicTask__ArgProps,
          internalVariantPropNames: PlasmicTask__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicTask__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTask";
  } else {
    func.displayName = `PlasmicTask.${nodeName}`;
  }
  return func;
}

export const PlasmicTask = Object.assign(
  // Top-level PlasmicTask renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    textInput: makeNodeComponent("textInput"),
    button: makeNodeComponent("button"),

    // Metadata about props expected for PlasmicTask
    internalVariantProps: PlasmicTask__VariantProps,
    internalArgProps: PlasmicTask__ArgProps
  }
);

export default PlasmicTask;
/* prettier-ignore-end */
